draft: false
name: Fairy Top
description: ''
images:
  - /src/assets/productos/271134.jpg
  - /src/assets/productos/265813.jpg
  - /src/assets/productos/271208.jpg
  - /src/assets/productos/271176.jpg
tags:
  - encaje, elastizada, detalle puntilla
price: $23.000
order: 2
